---
".gitlab-ci.yml":
  delete: true
".travis.yml":
  dist: trusty
  deploy_to_forge:
    enabled: false
  branches:
  - release
  user: puppet
  secure: ''
  includes:
  - bundler_args: 
    dist: trusty
    env: PLATFORMS=deb_puppet5
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_deb]'
    - bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
    - bundle exec rake 'litmus:install_agent[puppet5]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    stage: acceptance
    sudo: required
  - bundler_args: 
    dist: trusty
    env: PLATFORM=centos:deb_puppet6
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_deb]'
    - bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
    - bundle exec rake 'litmus:install_agent[puppet6]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
  - bundler_args: 
    dist: trusty
    env: PLATFORMS=el_puppet5
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_el]'
    - bundle exec rake 'litmus:install_agent[puppet5]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
  - bundler_args: 
    dist: trusty
    env: PLATFORM=centos:el_puppet6
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_el]'
    - bundle exec rake 'litmus:install_agent[puppet6]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    stage: acceptance
    sudo: required
  simplecov: true
  notifications:
    slack:
      secure: >-
        e9F4WyhqzG+sMkVI54lf93+HM7o0KIf8xRXVTTNxBhQslboob9uDjkOe/cNSrMKJNLau63pwD9uGbqkLehDbLey9djJV/yyEnbDW599NHd9puNvtKk+Yxqe5WDD9p3qZqBi8hkPMUfHbRU3ViqCMmPeHk+83sD+Dq5Qs7EYI8VKYOnhP5v0Lw7G+eWbpt0CV/Ddur7/wwR0e4amMgumFlU++Kd8/ZBFmePMK35CODr7Gnnlq/6EI0u73qzv6PsMAgbqVEU2rdcGBrfZq4q2dCdYSzQEEXMUMuOwEhxT1txuIcofFcXzqq5YzHHgh0gr/9ccbBXzSRKxoI1MTOM6cCvXVhKInAJknOF2kyOJa60h8sxkmia4WLP9baAdTD/SbzZgOksrucMPIaak9DkNYgsqHauwCzxqf8S/tfvvTNtiHoods4zX+HE5yUeOhSU6RylBSNOuo6ZeKMkdOS4k6wDEtwKR3H4XWhtQOI2y9lQwQsDpRq3w8JFwljr4MZTrJFzvRsf//spgTC+Wk0BU31Gr3KEDR5x4ahLpRAYl2/iwfH7vb5rrNktCcxzx+AqRusVout4AEEvKH8WmhGzDo564Ll3Wg7uWw4+5T6WTpsTW9vnWhQ1/K1Yd1SVSFSxDgzqyTgXarl6Uf1qSWDKOwPGb+JSpVsg3WuiVNh3utkCw=
".yardopts":
  optional:
  - "--output-dir docs/"
appveyor.yml:
  simplecov: true
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
      git: https://github.com/skywinder/github-changelog-generator
      ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
Rakefile:
  requires:
  - puppet-lint/tasks/puppet-lint
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
